
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

# Uncomment to update deps with dep tool
# ignored = ["github.com/kubernetes-incubator/apiserver-builder","github.com/kubernetes-incubator/apiserver-builder/cmd"]

required = [
  "github.com/json-iterator/go",
  "github.com/coreos/etcd",
  "google.golang.org/genproto",
  "google.golang.org/grpc",
  "github.com/imdario/mergo",
  "k8s.io/kube-openapi/cmd/openapi-gen",
  "github.com/modern-go/reflect2",
]

# Comment to update deps with dep tool
[[constraint]]
  version = "v0.1-alpha.28"
  name = "github.com/kubernetes-incubator/apiserver-builder"

[[constraint]]
  name = "github.com/emicklei/go-restful"

[[constraint]]
  name = "github.com/go-openapi/loads"

[[constraint]]
  name = "github.com/go-openapi/runtime"

[[constraint]]
  name = "github.com/go-openapi/spec"

[[constraint]]
  name = "github.com/go-openapi/validate"

[[constraint]]
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/markbates/inflect"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"

[[constraint]]
  name = "github.com/spf13/viper"

[[constraint]]
  branch = "release-1.12"
  name = "k8s.io/api"

[[constraint]]
  branch = "release-1.12"
  name = "k8s.io/apiextensions-apiserver"

[[constraint]]
  branch = "release-1.12"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "release-1.12"
  name = "k8s.io/apiserver"

[[constraint]]
  branch = "release-9.0"
  name = "k8s.io/client-go"

[[constraint]]
  name = "k8s.io/gengo"
  revision = "fdcf9f9480fdd5bf2b3c3df9bf4ecd22b25b87e2"

[[constraint]]
  name = "k8s.io/kube-openapi"
  revision = "0cf8f7e6ed1d2e3d47d02e3b6e559369af24d803"

[[constraint]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "=3.2.24"

[[constraint]]
  name = "google.golang.org/genproto"
  revision = "09f6ed296fc66555a25fe4ce95173148778dfa85"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "b4deda0973fb4c70b50d226b1af49f3da59f5265"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "=1.7.5"

[[constraint]]
  name = "github.com/imdario/mergo"
  version = "=0.3.5"

[[constraint]]
  name = "github.com/modern-go/reflect2"
  version = "1.0.1"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "=10.14.0"

[prune]
  unused-packages = true
  non-go = true
